export const countries = [
    { name: "Rwanda", code: "+250", flag: "🇷🇼" },
    { name: "United States", code: "+1", flag: "🇺🇸" },
    { name: "Singapore", code: "+65", flag: "🇸🇬" },
    { name: "United Kingdom", code: "+44", flag: "🇬🇧" },
    { name: "Canada", code: "+1", flag: "🇨🇦" },
    { name: "Australia", code: "+61", flag: "🇦🇺" },
    { name: "Germany", code: "+49", flag: "🇩🇪" },
    { name: "France", code: "+33", flag: "🇫🇷" },
    { name: "India", code: "+91", flag: "🇮🇳" },
    { name: "China", code: "+86", flag: "🇨🇳" },
    { name: "Japan", code: "+81", flag: "🇯🇵" },
    { name: "South Korea", code: "+82", flag: "🇰🇷" },
    { name: "Brazil", code: "+55", flag: "🇧🇷" },
    { name: "Mexico", code: "+52", flag: "🇲🇽" },
    { name: "South Africa", code: "+27", flag: "🇿🇦" },
    { name: "Nigeria", code: "+234", flag: "🇳🇬" },
    { name: "Kenya", code: "+254", flag: "🇰🇪" },
    { name: "Uganda", code: "+256", flag: "🇺🇬" },
    { name: "Tanzania", code: "+255", flag: "🇹🇿" },
    { name: "UAE", code: "+971", flag: "🇦🇪" },
    { name: "Saudi Arabia", code: "+966", flag: "🇸🇦" },
    { name: "Israel", code: "+972", flag: "🇮🇱" },
    { name: "Turkey", code: "+90", flag: "🇹🇷" },
    { name: "Spain", code: "+34", flag: "🇪🇸" },
    { name: "Italy", code: "+39", flag: "🇮🇹" },
    { name: "Netherlands", code: "+31", flag: "🇳🇱" },
    { name: "Sweden", code: "+46", flag: "🇸🇪" },
    { name: "Norway", code: "+47", flag: "🇳🇴" },
    { name: "Russia", code: "+7", flag: "🇷🇺" },
    { name: "Thailand", code: "+66", flag: "🇹🇭" },
    { name: "Vietnam", code: "+84", flag: "🇻🇳" },
    { name: "Indonesia", code: "+62", flag: "🇮🇩" },
    { name: "Malaysia", code: "+60", flag: "🇲🇾" },
    { name: "Philippines", code: "+63", flag: "🇵🇭" },
    { name: "New Zealand", code: "+64", flag: "🇳🇿" }
];
